# Generated by Django 2.2.7 on 2019-12-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0002_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=25)),
                ('bookname', models.CharField(max_length=25)),
            ],
        ),
    ]
