# Generated by Django 2.2.7 on 2019-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0004_books_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
