# Generated by Django 2.2.7 on 2019-12-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0005_auto_20191203_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow1',
            name='custid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow1',
            name='isbn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
