# Generated by Django 2.2.7 on 2019-12-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0006_auto_20191204_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow1',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='borrow1',
            name='isbn',
        ),
    ]
